### ISSUE TITLE
Not actually working

### ISSUE THREAD

**Issue by PavelVanecek** [rstacruz/mocha-eventually#1]
I did not get this lib working.

When I copy the example from README:

```
var eventually = require('mocha-eventually')

it('eventually works', function () {
  return eventually(function (next) {
    assert(Math.random() > 0.9)
  }, 2000)
})
```

And run it with mocha, I get this result:

```
  1) eventually works

  0 passing (2s)
  1 failing

  1)  eventually works:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Also reproducible with pretty much all other examples I tried.

Using:
- node.js 5.3.0
- mocha 2.3.4
- mocha-eventually 1.1.0

**Comment by rstacruz** [comment]
oops... something's wrong with that example; you'll need to trigger `next()` after.

``` js
it('eventually works', function () {
  return eventually(function (next) {
    assert(Math.random() > 0.9)
    next()
  }, 2000)
})
```

**Comment by PavelVanecek** [comment]
Is it possible to mimick the behaviour of Mocha? That means:
1. If (callback.length === 1) then wait until `next` is called
2. If (callback returned promise) then hook on that promise
3. if (callback thrown an error) test failed
4. else test passed

From what I am seeing here, if callback.length === 0 this module still waits until `next()` call even though I never asked for it in my test.

It means this scenario:

```
eventually(function() { // no "next" here
  assert.ok(true);
  // no other call, test passed; but mocha-eventually fails due to timeout
})
```

**Comment by rstacruz** [comment]
It does mimic the behavior of mocha in the way you outlined. Yes, it'll
take care of promises. In mocha, if you don't call the callback (and you
asked for one), the test will time out. :-)

**Comment by rstacruz** [comment]
Ah wait, yeah, it looks like the arity check is missing, that can be fixed

**Comment by PavelVanecek** [comment]
The arity check was in place, but with a small bug. I fixed it in the PR.
